name: Update Profile README stats
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main

jobs:
  github-profile-summary:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            snake/github-snake.svg

      # Commit back
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update snake
          file_pattern: "snake/*.svg"

      # https://github.com/lowlighter/metrics
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/reactions/README.md
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
          plugin_calendar: yes
          plugin_calendar_limit: 3

          plugin_languages: yes
          plugin_achievements: yes