name: Update Profile README stats

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow on push to main
  push:
    branches:
      - main

jobs:
  github-profile-summary:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build optimized Docker image
      - name: Build custom Docker image
        run: |
          docker build -t github-metrics-image ./docker

      # 3️⃣ Run the metrics scripts inside Docker
      - name: Run metrics scripts
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/metrics \
            github-metrics-image \
            /bin/sh -c "/metrics/source/app/action/index.mjs"

      # 4️⃣ Commit updated snake SVGs
      - name: Commit snake updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake and metrics"
          file_pattern: |
            snake/*.svg
            github-metrics.svg

      # 5️⃣ Optional: output logs
      - name: Show Docker version
        run: docker --version
